
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Jul 18 2024 16:49:14 IST (Jul 18 2024 11:19:14 UTC)

// Verification Directory fv/up_counter 

module up_counter(clk_pad, reset_pad, counter_pad);
  input clk_pad, reset_pad;
  output [3:0] counter_pad;
  wire clk_pad, reset_pad;
  wire [3:0] counter_pad;
  wire [3:0] counter_up;
  wire clk, clk_b, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, reset;
  pc3c01 pc3c01_1(.CCLK (clk_b), .CP (clk));
  pc3d01 pc3d01_1(.PAD (clk_pad), .CIN (clk_b));
  pc3d01 pc3d01_2(.PAD (reset_pad), .CIN (reset));
  pc3o05 pc3o05_1(.I (counter_up[3]), .PAD (counter_pad[3]));
  pc3o05 pc3o05_2(.I (counter_up[2]), .PAD (counter_pad[2]));
  pc3o05 pc3o05_3(.I (counter_up[1]), .PAD (counter_pad[1]));
  pc3o05 pc3o05_4(.I (counter_up[0]), .PAD (counter_pad[0]));
  pvdi   pvdi_VDD_CORE   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0i   pv0i_VSS_CORE   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda   pvda_VDDO_CORE  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a   pv0a_VSSO_CORE  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  dfcrq1 \counter_up_reg[3] (.CDN (n_1), .CP (clk), .D (n_5), .Q
       (counter_up[3]));
  oaim22d1 g65__2398(.A1 (n_4), .A2 (counter_up[3]), .B1 (n_4), .B2
       (counter_up[3]), .ZN (n_5));
  dfcrq1 \counter_up_reg[2] (.CDN (n_1), .CP (clk), .D (n_0), .Q
       (counter_up[2]));
  dfcrq1 \counter_up_reg[1] (.CDN (n_1), .CP (clk), .D (n_2), .Q
       (counter_up[1]));
  nd02d1 g70__5107(.A1 (n_3), .A2 (counter_up[2]), .ZN (n_4));
  ah01d1 g71__6260(.A (counter_up[1]), .B (counter_up[0]), .CO (n_3),
       .S (n_2));
  inv0d0 g74(.I (reset), .ZN (n_1));
  ora21d1 g2__4319(.A (n_4), .B1 (n_3), .B2 (counter_up[2]), .Z (n_0));
  dfcrb1 \counter_up_reg[0] (.CDN (n_1), .CP (clk), .D (n_6), .Q
       (counter_up[0]), .QN (n_6));
endmodule

