
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Feb  5 2024 23:59:39 IST (Feb  5 2024 18:29:39 UTC)

// Verification Directory fv/fifo 

module fifo_empty_ADDRSIZE4(i_rd_clk, i_rd_rst_n, i_rd_en,
     i_wr_ptr_clx, o_empty, o_rd_addr, o_rd_ptr);
  input i_rd_clk, i_rd_rst_n, i_rd_en;
  input [4:0] i_wr_ptr_clx;
  output o_empty;
  output [3:0] o_rd_addr;
  output [4:0] o_rd_ptr;
  wire i_rd_clk, i_rd_rst_n, i_rd_en;
  wire [4:0] i_wr_ptr_clx;
  wire o_empty;
  wire [3:0] o_rd_addr;
  wire [4:0] o_rd_ptr;
  wire [4:0] rd_gray_next_s;
  wire [4:0] rd_bin_next_s;
  wire UNCONNECTED, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17;
  inv0d0 g136(.I (i_rd_en), .ZN (n_17));
  dfcrq1 \o_rd_ptr_reg[3] (.CDN (i_rd_rst_n), .CP (i_rd_clk), .D
       (rd_gray_next_s[3]), .Q (o_rd_ptr[3]));
  mx02d1 g183__2398(.I0 (rd_bin_next_s[4]), .I1 (n_16), .S
       (rd_bin_next_s[3]), .Z (rd_gray_next_s[3]));
  dfcrq1 \o_rd_ptr_reg[2] (.CDN (i_rd_rst_n), .CP (i_rd_clk), .D
       (rd_gray_next_s[2]), .Q (o_rd_ptr[2]));
  inv0d0 g185(.I (n_16), .ZN (rd_bin_next_s[4]));
  aoim22d1 g186__5107(.A1 (n_15), .A2 (n_10), .B1 (n_15), .B2 (n_10),
       .Z (n_16));
  xr02d1 g187__6260(.A1 (rd_bin_next_s[3]), .A2 (rd_bin_next_s[2]), .Z
       (rd_gray_next_s[2]));
  ah01d1 g188__4319(.A (n_14), .B (o_rd_addr[3]), .CO (n_15), .S
       (rd_bin_next_s[3]));
  dfcrq1 \o_rd_ptr_reg[1] (.CDN (i_rd_rst_n), .CP (i_rd_clk), .D
       (rd_gray_next_s[1]), .Q (o_rd_ptr[1]));
  xr02d1 g190__8428(.A1 (rd_bin_next_s[2]), .A2 (rd_bin_next_s[1]), .Z
       (rd_gray_next_s[1]));
  ah01d1 g191__5526(.A (n_13), .B (o_rd_addr[2]), .CO (n_14), .S
       (rd_bin_next_s[2]));
  dfcrq1 \o_rd_ptr_reg[0] (.CDN (i_rd_rst_n), .CP (i_rd_clk), .D
       (rd_gray_next_s[0]), .Q (o_rd_ptr[0]));
  xr02d1 g193__6783(.A1 (rd_bin_next_s[1]), .A2 (rd_bin_next_s[0]), .Z
       (rd_gray_next_s[0]));
  ah01d1 g194__3680(.A (n_12), .B (o_rd_addr[1]), .CO (n_13), .S
       (rd_bin_next_s[1]));
  ah01d1 g195__1617(.A (n_11), .B (o_rd_addr[0]), .CO (n_12), .S
       (rd_bin_next_s[0]));
  nr02d1 g196__2802(.A1 (o_empty), .A2 (n_17), .ZN (n_11));
  dfprb1 empty_r_reg(.SDN (i_rd_rst_n), .CP (i_rd_clk), .D (n_9), .Q
       (o_empty), .QN (UNCONNECTED));
  oan211d1 g198__1705(.A (n_8), .B (n_3), .C1 (rd_bin_next_s[4]), .C2
       (i_wr_ptr_clx[4]), .ZN (n_9));
  nd04d1 g199__5122(.A1 (n_5), .A2 (n_7), .A3 (n_4), .A4 (n_6), .ZN
       (n_8));
  oaim22d1 g200__8246(.A1 (rd_gray_next_s[3]), .A2 (i_wr_ptr_clx[3]),
       .B1 (rd_gray_next_s[3]), .B2 (i_wr_ptr_clx[3]), .ZN (n_7));
  aoim22d1 g201__7098(.A1 (rd_gray_next_s[0]), .A2 (n_1), .B1
       (rd_gray_next_s[0]), .B2 (n_1), .Z (n_6));
  aoim22d1 g202__6131(.A1 (rd_gray_next_s[1]), .A2 (n_2), .B1
       (rd_gray_next_s[1]), .B2 (n_2), .Z (n_5));
  aoim22d1 g203__1881(.A1 (rd_gray_next_s[2]), .A2 (n_0), .B1
       (rd_gray_next_s[2]), .B2 (n_0), .Z (n_4));
  dfcrq1 \rd_bin_r_reg[0] (.CDN (i_rd_rst_n), .CP (i_rd_clk), .D
       (rd_bin_next_s[0]), .Q (o_rd_addr[0]));
  dfcrq1 \rd_bin_r_reg[1] (.CDN (i_rd_rst_n), .CP (i_rd_clk), .D
       (rd_bin_next_s[1]), .Q (o_rd_addr[1]));
  dfcrq1 \rd_bin_r_reg[3] (.CDN (i_rd_rst_n), .CP (i_rd_clk), .D
       (rd_bin_next_s[3]), .Q (o_rd_addr[3]));
  dfcrq1 \rd_bin_r_reg[2] (.CDN (i_rd_rst_n), .CP (i_rd_clk), .D
       (rd_bin_next_s[2]), .Q (o_rd_addr[2]));
  nd02d1 g207__5115(.A1 (rd_bin_next_s[4]), .A2 (i_wr_ptr_clx[4]), .ZN
       (n_3));
  inv0d0 g208(.I (i_wr_ptr_clx[1]), .ZN (n_2));
  inv0d0 g209(.I (i_wr_ptr_clx[0]), .ZN (n_1));
  inv0d0 g210(.I (i_wr_ptr_clx[2]), .ZN (n_0));
  dfcrb1 \o_rd_ptr_reg[4] (.CDN (i_rd_rst_n), .CP (i_rd_clk), .D
       (rd_bin_next_s[4]), .Q (o_rd_ptr[4]), .QN (n_10));
endmodule

module fifo_full_ADDRSIZE4(i_wr_clk, i_wr_rst_n, i_wr_en, i_rd_ptr_clx,
     o_full, o_wr_addr, o_wr_ptr);
  input i_wr_clk, i_wr_rst_n, i_wr_en;
  input [4:0] i_rd_ptr_clx;
  output o_full;
  output [3:0] o_wr_addr;
  output [4:0] o_wr_ptr;
  wire i_wr_clk, i_wr_rst_n, i_wr_en;
  wire [4:0] i_rd_ptr_clx;
  wire o_full;
  wire [3:0] o_wr_addr;
  wire [4:0] o_wr_ptr;
  wire [4:0] wr_gray_next_s;
  wire [4:0] wr_bin_next_s;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18;
  inv0d0 g161(.I (i_wr_en), .ZN (n_18));
  dfcrq1 \o_wr_ptr_reg[3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (wr_gray_next_s[3]), .Q (o_wr_ptr[3]));
  dfcrq1 \o_wr_ptr_reg[2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (wr_gray_next_s[2]), .Q (o_wr_ptr[2]));
  oai22d1 g219__7482(.A1 (n_17), .A2 (wr_bin_next_s[4]), .B1 (n_14),
       .B2 (wr_bin_next_s[3]), .ZN (wr_gray_next_s[3]));
  mx02d1 g220__4733(.I0 (wr_bin_next_s[3]), .I1 (n_17), .S
       (wr_bin_next_s[2]), .Z (wr_gray_next_s[2]));
  dfcrq1 \o_wr_ptr_reg[1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (wr_gray_next_s[1]), .Q (o_wr_ptr[1]));
  xr02d1 g222__6161(.A1 (wr_bin_next_s[2]), .A2 (wr_bin_next_s[1]), .Z
       (wr_gray_next_s[1]));
  inv0d0 g223(.I (n_17), .ZN (wr_bin_next_s[3]));
  aoim22d1 g224__9315(.A1 (n_16), .A2 (o_wr_addr[3]), .B1 (n_16), .B2
       (o_wr_addr[3]), .Z (n_17));
  inv0d0 g225(.I (n_15), .ZN (n_16));
  ah01d1 g226__9945(.A (n_12), .B (o_wr_addr[2]), .CO (n_15), .S
       (wr_bin_next_s[2]));
  dfcrq1 \o_wr_ptr_reg[0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (wr_gray_next_s[0]), .Q (o_wr_ptr[0]));
  inv0d0 g228(.I (n_14), .ZN (wr_bin_next_s[4]));
  aoim22d1 g229__2883(.A1 (n_13), .A2 (o_wr_ptr[4]), .B1 (n_13), .B2
       (o_wr_ptr[4]), .Z (n_14));
  xr02d1 g230__2346(.A1 (wr_bin_next_s[1]), .A2 (wr_bin_next_s[0]), .Z
       (wr_gray_next_s[0]));
  nd03d1 g231__1666(.A1 (n_12), .A2 (o_wr_addr[3]), .A3 (o_wr_addr[2]),
       .ZN (n_13));
  ah01d1 g232__7410(.A (n_11), .B (o_wr_addr[1]), .CO (n_12), .S
       (wr_bin_next_s[1]));
  ah01d1 g233__6417(.A (n_10), .B (o_wr_addr[0]), .CO (n_11), .S
       (wr_bin_next_s[0]));
  nr02d1 g234__5477(.A1 (o_full), .A2 (n_18), .ZN (n_10));
  dfcrq1 full_r_reg(.CDN (i_wr_rst_n), .CP (i_wr_clk), .D (n_9), .Q
       (o_full));
  nr04d1 g235__2398(.A1 (n_5), .A2 (n_8), .A3 (n_7), .A4 (n_4), .ZN
       (n_9));
  aon211d1 g236__5107(.A (n_6), .B (n_3), .C1 (wr_gray_next_s[1]), .C2
       (i_rd_ptr_clx[1]), .ZN (n_8));
  xr02d1 g237__6260(.A1 (wr_gray_next_s[2]), .A2 (i_rd_ptr_clx[2]), .Z
       (n_7));
  aoim22d1 g238__4319(.A1 (wr_gray_next_s[0]), .A2 (n_1), .B1
       (wr_gray_next_s[0]), .B2 (n_1), .Z (n_6));
  aoim22d1 g227__8428(.A1 (wr_bin_next_s[4]), .A2 (n_0), .B1
       (wr_bin_next_s[4]), .B2 (n_0), .Z (n_5));
  aoim22d1 g239__5526(.A1 (wr_gray_next_s[3]), .A2 (n_2), .B1
       (wr_gray_next_s[3]), .B2 (n_2), .Z (n_4));
  dfcrq1 \o_wr_ptr_reg[4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (wr_bin_next_s[4]), .Q (o_wr_ptr[4]));
  dfcrq1 \wr_bin_r_reg[0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (wr_bin_next_s[0]), .Q (o_wr_addr[0]));
  dfcrq1 \wr_bin_r_reg[1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (wr_bin_next_s[1]), .Q (o_wr_addr[1]));
  dfcrq1 \wr_bin_r_reg[3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (wr_bin_next_s[3]), .Q (o_wr_addr[3]));
  dfcrq1 \wr_bin_r_reg[2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (wr_bin_next_s[2]), .Q (o_wr_addr[2]));
  nr02d1 g240__6783(.A1 (i_rd_ptr_clx[1]), .A2 (wr_gray_next_s[1]), .ZN
       (n_3));
  inv0d0 g241(.I (i_rd_ptr_clx[3]), .ZN (n_2));
  inv0d0 g242(.I (i_rd_ptr_clx[0]), .ZN (n_1));
  inv0d0 g243(.I (i_rd_ptr_clx[4]), .ZN (n_0));
endmodule

module fifo_mem_DATASIZE8_ADDRSIZE4_MEM_DEPTH16(o_rd_data, i_full,
     i_wr_data, i_wr_clk, i_wr_en, i_wr_addr, i_rd_addr, i_wr_rst_n);
  input i_full, i_wr_clk, i_wr_en, i_wr_rst_n;
  input [7:0] i_wr_data;
  input [3:0] i_wr_addr, i_rd_addr;
  output [7:0] o_rd_data;
  wire i_full, i_wr_clk, i_wr_en, i_wr_rst_n;
  wire [7:0] i_wr_data;
  wire [3:0] i_wr_addr, i_rd_addr;
  wire [7:0] o_rd_data;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[14] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_144;
  aor211d1 g3093__3680(.A (n_122), .B (n_111), .C1 (n_50), .C2
       (\mem[5] [2]), .Z (o_rd_data[2]));
  aor211d1 g3094__1617(.A (n_116), .B (n_113), .C1 (n_26), .C2
       (\mem[1] [6]), .Z (o_rd_data[6]));
  aor211d1 g3095__2802(.A (n_120), .B (n_112), .C1 (n_48), .C2
       (\mem[2] [7]), .Z (o_rd_data[7]));
  aor211d1 g3096__1705(.A (n_119), .B (n_110), .C1 (n_38), .C2
       (\mem[13] [1]), .Z (o_rd_data[1]));
  aor211d1 g3097__5122(.A (n_121), .B (n_106), .C1 (n_50), .C2
       (\mem[5] [5]), .Z (o_rd_data[5]));
  aor211d1 g3098__8246(.A (n_118), .B (n_108), .C1 (n_46), .C2
       (\mem[15] [0]), .Z (o_rd_data[0]));
  aor211d1 g3099__7098(.A (n_117), .B (n_107), .C1 (n_38), .C2
       (\mem[13] [4]), .Z (o_rd_data[4]));
  aor211d1 g3100__6131(.A (n_115), .B (n_109), .C1 (n_36), .C2
       (\mem[0] [3]), .Z (o_rd_data[3]));
  aor221d1 g3101__1881(.A (n_114), .B1 (n_36), .B2 (\mem[0] [2]), .C1
       (n_26), .C2 (\mem[1] [2]), .Z (n_122));
  nd04d1 g3102__5115(.A1 (n_81), .A2 (n_87), .A3 (n_99), .A4 (n_84),
       .ZN (n_121));
  nd04d1 g3103__7482(.A1 (n_72), .A2 (n_100), .A3 (n_60), .A4 (n_88),
       .ZN (n_120));
  nd04d1 g3104__4733(.A1 (n_77), .A2 (n_76), .A3 (n_75), .A4 (n_104),
       .ZN (n_119));
  nd04d1 g3105__6161(.A1 (n_69), .A2 (n_65), .A3 (n_103), .A4 (n_67),
       .ZN (n_118));
  nd04d1 g3106__9315(.A1 (n_102), .A2 (n_66), .A3 (n_68), .A4 (n_62),
       .ZN (n_117));
  nd04d1 g3107__9945(.A1 (n_63), .A2 (n_70), .A3 (n_101), .A4 (n_59),
       .ZN (n_116));
  nd04d1 g3108__2883(.A1 (n_52), .A2 (n_56), .A3 (n_105), .A4 (n_54),
       .ZN (n_115));
  nd04d1 g3109__2346(.A1 (n_82), .A2 (n_83), .A3 (n_86), .A4 (n_85),
       .ZN (n_114));
  nd02d1 g3110__1666(.A1 (n_98), .A2 (n_79), .ZN (n_113));
  nd02d1 g3111__7410(.A1 (n_96), .A2 (n_55), .ZN (n_112));
  nd02d1 g3112__6417(.A1 (n_97), .A2 (n_89), .ZN (n_111));
  nd02d1 g3113__5477(.A1 (n_95), .A2 (n_80), .ZN (n_110));
  nd02d1 g3114__2398(.A1 (n_91), .A2 (n_58), .ZN (n_109));
  nd02d1 g3115__5107(.A1 (n_92), .A2 (n_71), .ZN (n_108));
  nd02d1 g3116__6260(.A1 (n_93), .A2 (n_74), .ZN (n_107));
  nd02d1 g3117__4319(.A1 (n_94), .A2 (n_51), .ZN (n_106));
  aoi221d1 g3118__8428(.A (n_90), .B1 (n_42), .B2 (\mem[10] [3]), .C1
       (\mem[11] [3]), .C2 (n_37), .ZN (n_105));
  aoi221d1 g3119__5526(.A (n_73), .B1 (n_48), .B2 (\mem[2] [1]), .C1
       (\mem[3] [1]), .C2 (n_41), .ZN (n_104));
  aoi221d1 g3120__6783(.A (n_64), .B1 (n_36), .B2 (\mem[0] [0]), .C1
       (\mem[1] [0]), .C2 (n_26), .ZN (n_103));
  aoi221d1 g3121__3680(.A (n_61), .B1 (n_36), .B2 (\mem[0] [4]), .C1
       (\mem[1] [4]), .C2 (n_26), .ZN (n_102));
  aoi221d1 g3122__1617(.A (n_57), .B1 (n_42), .B2 (\mem[10] [6]), .C1
       (\mem[11] [6]), .C2 (n_37), .ZN (n_101));
  aoi221d1 g3123__2802(.A (n_53), .B1 (n_39), .B2 (\mem[12] [7]), .C1
       (\mem[13] [7]), .C2 (n_38), .ZN (n_100));
  aoi221d1 g3124__1705(.A (n_78), .B1 (n_42), .B2 (\mem[10] [5]), .C1
       (\mem[11] [5]), .C2 (n_37), .ZN (n_99));
  aoi222d1 g3125__5122(.A1 (\mem[7] [6]), .A2 (n_44), .B1 (n_45), .B2
       (\mem[4] [6]), .C1 (\mem[5] [6]), .C2 (n_50), .ZN (n_98));
  aoi222d1 g3126__8246(.A1 (\mem[2] [2]), .A2 (n_48), .B1 (n_43), .B2
       (\mem[6] [2]), .C1 (\mem[3] [2]), .C2 (n_41), .ZN (n_97));
  aoi222d1 g3127__7098(.A1 (\mem[6] [7]), .A2 (n_43), .B1 (n_26), .B2
       (\mem[1] [7]), .C1 (\mem[7] [7]), .C2 (n_44), .ZN (n_96));
  aoi222d1 g3128__6131(.A1 (\mem[10] [1]), .A2 (n_42), .B1 (n_47), .B2
       (\mem[8] [1]), .C1 (\mem[9] [1]), .C2 (n_40), .ZN (n_95));
  aoi222d1 g3129__1881(.A1 (\mem[0] [5]), .A2 (n_36), .B1 (n_41), .B2
       (\mem[3] [5]), .C1 (\mem[1] [5]), .C2 (n_26), .ZN (n_94));
  aoi222d1 g3130__5115(.A1 (\mem[10] [4]), .A2 (n_42), .B1 (n_49), .B2
       (\mem[14] [4]), .C1 (\mem[11] [4]), .C2 (n_37), .ZN (n_93));
  aoi222d1 g3131__7482(.A1 (\mem[12] [0]), .A2 (n_39), .B1 (n_47), .B2
       (\mem[8] [0]), .C1 (\mem[13] [0]), .C2 (n_38), .ZN (n_92));
  aoi222d1 g3132__4733(.A1 (\mem[7] [3]), .A2 (n_44), .B1 (n_45), .B2
       (\mem[4] [3]), .C1 (\mem[5] [3]), .C2 (n_50), .ZN (n_91));
  aor22d1 g3133__6161(.A1 (n_47), .A2 (\mem[8] [3]), .B1 (n_40), .B2
       (\mem[9] [3]), .Z (n_90));
  aoi22d1 g3134__9315(.A1 (n_45), .A2 (\mem[4] [2]), .B1 (n_44), .B2
       (\mem[7] [2]), .ZN (n_89));
  aoi22d1 g3135__9945(.A1 (n_45), .A2 (\mem[4] [7]), .B1 (n_50), .B2
       (\mem[5] [7]), .ZN (n_88));
  aoi22d1 g3136__2883(.A1 (n_43), .A2 (\mem[6] [5]), .B1 (n_44), .B2
       (\mem[7] [5]), .ZN (n_87));
  aoi22d1 g3137__2346(.A1 (n_47), .A2 (\mem[8] [2]), .B1 (n_40), .B2
       (\mem[9] [2]), .ZN (n_86));
  aoi22d1 g3138__1666(.A1 (n_39), .A2 (\mem[12] [2]), .B1 (n_38), .B2
       (\mem[13] [2]), .ZN (n_85));
  aoi22d1 g3139__7410(.A1 (n_39), .A2 (\mem[12] [5]), .B1 (n_38), .B2
       (\mem[13] [5]), .ZN (n_84));
  aoi22d1 g3140__6417(.A1 (n_49), .A2 (\mem[14] [2]), .B1 (n_46), .B2
       (\mem[15] [2]), .ZN (n_83));
  aoi22d1 g3141__5477(.A1 (n_42), .A2 (\mem[10] [2]), .B1 (n_37), .B2
       (\mem[11] [2]), .ZN (n_82));
  aoi22d1 g3142__2398(.A1 (n_47), .A2 (\mem[8] [5]), .B1 (n_40), .B2
       (\mem[9] [5]), .ZN (n_81));
  aoi22d1 g3143__5107(.A1 (n_39), .A2 (\mem[12] [1]), .B1 (n_37), .B2
       (\mem[11] [1]), .ZN (n_80));
  aoi22d1 g3144__6260(.A1 (n_36), .A2 (\mem[0] [6]), .B1 (n_43), .B2
       (\mem[6] [6]), .ZN (n_79));
  aor22d1 g3145__4319(.A1 (n_49), .A2 (\mem[14] [5]), .B1 (n_46), .B2
       (\mem[15] [5]), .Z (n_78));
  aoi22d1 g3146__8428(.A1 (n_49), .A2 (\mem[14] [1]), .B1 (n_46), .B2
       (\mem[15] [1]), .ZN (n_77));
  aoi22d1 g3147__5526(.A1 (n_43), .A2 (\mem[6] [1]), .B1 (n_44), .B2
       (\mem[7] [1]), .ZN (n_76));
  aoi22d1 g3148__6783(.A1 (n_36), .A2 (\mem[0] [1]), .B1 (n_26), .B2
       (\mem[1] [1]), .ZN (n_75));
  aoi22d1 g3149__3680(.A1 (n_39), .A2 (\mem[12] [4]), .B1 (n_46), .B2
       (\mem[15] [4]), .ZN (n_74));
  aor22d1 g3150__1617(.A1 (n_45), .A2 (\mem[4] [1]), .B1 (n_50), .B2
       (\mem[5] [1]), .Z (n_73));
  aoi22d1 g3151__2802(.A1 (n_42), .A2 (\mem[10] [7]), .B1 (n_37), .B2
       (\mem[11] [7]), .ZN (n_72));
  aoi22d1 g3152__1705(.A1 (n_40), .A2 (\mem[9] [0]), .B1 (n_49), .B2
       (\mem[14] [0]), .ZN (n_71));
  aoi22d1 g3153__5122(.A1 (n_48), .A2 (\mem[2] [6]), .B1 (n_41), .B2
       (\mem[3] [6]), .ZN (n_70));
  aoi22d1 g3154__8246(.A1 (n_42), .A2 (\mem[10] [0]), .B1 (n_37), .B2
       (\mem[11] [0]), .ZN (n_69));
  aoi22d1 g3155__7098(.A1 (n_47), .A2 (\mem[8] [4]), .B1 (n_40), .B2
       (\mem[9] [4]), .ZN (n_68));
  aoi22d1 g3156__6131(.A1 (n_45), .A2 (\mem[4] [0]), .B1 (n_50), .B2
       (\mem[5] [0]), .ZN (n_67));
  aoi22d1 g3157__1881(.A1 (n_43), .A2 (\mem[6] [4]), .B1 (n_44), .B2
       (\mem[7] [4]), .ZN (n_66));
  aoi22d1 g3158__5115(.A1 (n_43), .A2 (\mem[6] [0]), .B1 (n_44), .B2
       (\mem[7] [0]), .ZN (n_65));
  aor22d1 g3159__7482(.A1 (n_48), .A2 (\mem[2] [0]), .B1 (n_41), .B2
       (\mem[3] [0]), .Z (n_64));
  aoi22d1 g3160__4733(.A1 (n_49), .A2 (\mem[14] [6]), .B1 (n_46), .B2
       (\mem[15] [6]), .ZN (n_63));
  aoi22d1 g3161__6161(.A1 (n_45), .A2 (\mem[4] [4]), .B1 (n_50), .B2
       (\mem[5] [4]), .ZN (n_62));
  aor22d1 g3162__9315(.A1 (n_48), .A2 (\mem[2] [4]), .B1 (n_41), .B2
       (\mem[3] [4]), .Z (n_61));
  aoi22d1 g3163__9945(.A1 (n_47), .A2 (\mem[8] [7]), .B1 (n_40), .B2
       (\mem[9] [7]), .ZN (n_60));
  aoi22d1 g3164__2883(.A1 (n_39), .A2 (\mem[12] [6]), .B1 (n_38), .B2
       (\mem[13] [6]), .ZN (n_59));
  aoi22d1 g3165__2346(.A1 (n_26), .A2 (\mem[1] [3]), .B1 (n_43), .B2
       (\mem[6] [3]), .ZN (n_58));
  aor22d1 g3166__1666(.A1 (n_47), .A2 (\mem[8] [6]), .B1 (n_40), .B2
       (\mem[9] [6]), .Z (n_57));
  aoi22d1 g3167__7410(.A1 (n_48), .A2 (\mem[2] [3]), .B1 (n_41), .B2
       (\mem[3] [3]), .ZN (n_56));
  aoi22d1 g3168__6417(.A1 (n_36), .A2 (\mem[0] [7]), .B1 (n_41), .B2
       (\mem[3] [7]), .ZN (n_55));
  aoi22d1 g3169__5477(.A1 (n_39), .A2 (\mem[12] [3]), .B1 (n_38), .B2
       (\mem[13] [3]), .ZN (n_54));
  aor22d1 g3170__2398(.A1 (n_49), .A2 (\mem[14] [7]), .B1 (n_46), .B2
       (\mem[15] [7]), .Z (n_53));
  aoi22d1 g3171__5107(.A1 (n_49), .A2 (\mem[14] [3]), .B1 (n_46), .B2
       (\mem[15] [3]), .ZN (n_52));
  aoi22d1 g3172__6260(.A1 (n_45), .A2 (\mem[4] [5]), .B1 (n_48), .B2
       (\mem[2] [5]), .ZN (n_51));
  nr02d1 g3173__4319(.A1 (n_35), .A2 (n_33), .ZN (n_50));
  nr02d1 g3174__8428(.A1 (n_31), .A2 (n_32), .ZN (n_49));
  nr02d1 g3175__5526(.A1 (n_30), .A2 (n_34), .ZN (n_48));
  nr02d1 g3176__6783(.A1 (n_29), .A2 (n_32), .ZN (n_47));
  nr02d1 g3177__3680(.A1 (n_31), .A2 (n_27), .ZN (n_46));
  nr02d1 g3178__1617(.A1 (n_30), .A2 (n_35), .ZN (n_45));
  nr02d1 g3180__2802(.A1 (n_31), .A2 (n_33), .ZN (n_44));
  nr02d1 g3181__1705(.A1 (n_30), .A2 (n_31), .ZN (n_43));
  nr02d1 g3182__5122(.A1 (n_32), .A2 (n_34), .ZN (n_42));
  nr02d1 g3183__8246(.A1 (n_34), .A2 (n_33), .ZN (n_41));
  nr02d1 g3184__7098(.A1 (n_29), .A2 (n_27), .ZN (n_40));
  nr02d1 g3185__6131(.A1 (n_32), .A2 (n_35), .ZN (n_39));
  nr02d1 g3186__1881(.A1 (n_27), .A2 (n_35), .ZN (n_38));
  nr02d1 g3187__5115(.A1 (n_27), .A2 (n_34), .ZN (n_37));
  nr02d1 g3188__7482(.A1 (n_30), .A2 (n_29), .ZN (n_36));
  nd12d1 g3190__4733(.A1 (i_rd_addr[1]), .A2 (i_rd_addr[2]), .ZN
       (n_35));
  nd12d1 g3191__6161(.A1 (i_rd_addr[2]), .A2 (i_rd_addr[1]), .ZN
       (n_34));
  nd12d1 g3192__9315(.A1 (i_rd_addr[3]), .A2 (i_rd_addr[0]), .ZN
       (n_33));
  nd12d1 g3193__9945(.A1 (i_rd_addr[0]), .A2 (i_rd_addr[3]), .ZN
       (n_32));
  inv0d0 g3194(.I (n_28), .ZN (n_29));
  nd02d1 g3195__2883(.A1 (i_rd_addr[2]), .A2 (i_rd_addr[1]), .ZN
       (n_31));
  or02d1 g3196__2346(.A1 (i_rd_addr[0]), .A2 (i_rd_addr[3]), .Z (n_30));
  nr02d1 g3197__1666(.A1 (i_rd_addr[1]), .A2 (i_rd_addr[2]), .ZN
       (n_28));
  nd02d1 g3198__7410(.A1 (i_rd_addr[3]), .A2 (i_rd_addr[0]), .ZN
       (n_27));
  an12d1 g2__6417(.A1 (n_33), .A2 (n_28), .Z (n_26));
  decrq1 \mem_reg[0][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_16), .Q (\mem[0] [0]));
  decrq1 \mem_reg[0][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_16), .Q (\mem[0] [1]));
  decrq1 \mem_reg[0][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_16), .Q (\mem[0] [2]));
  decrq1 \mem_reg[0][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_16), .Q (\mem[0] [3]));
  decrq1 \mem_reg[0][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_16), .Q (\mem[0] [4]));
  decrq1 \mem_reg[0][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_16), .Q (\mem[0] [5]));
  decrq1 \mem_reg[0][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_16), .Q (\mem[0] [6]));
  decrq1 \mem_reg[0][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_16), .Q (\mem[0] [7]));
  decrq1 \mem_reg[1][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_15), .Q (\mem[1] [0]));
  decrq1 \mem_reg[1][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_15), .Q (\mem[1] [1]));
  decrq1 \mem_reg[1][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_15), .Q (\mem[1] [2]));
  decrq1 \mem_reg[1][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_15), .Q (\mem[1] [3]));
  decrq1 \mem_reg[1][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_15), .Q (\mem[1] [4]));
  decrq1 \mem_reg[1][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_15), .Q (\mem[1] [5]));
  decrq1 \mem_reg[1][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_15), .Q (\mem[1] [6]));
  decrq1 \mem_reg[1][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_15), .Q (\mem[1] [7]));
  decrq1 \mem_reg[2][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_12), .Q (\mem[2] [0]));
  decrq1 \mem_reg[2][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_12), .Q (\mem[2] [1]));
  decrq1 \mem_reg[2][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_12), .Q (\mem[2] [2]));
  decrq1 \mem_reg[2][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_12), .Q (\mem[2] [3]));
  decrq1 \mem_reg[2][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_12), .Q (\mem[2] [4]));
  decrq1 \mem_reg[2][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_12), .Q (\mem[2] [5]));
  decrq1 \mem_reg[2][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_12), .Q (\mem[2] [6]));
  decrq1 \mem_reg[2][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_12), .Q (\mem[2] [7]));
  decrq1 \mem_reg[3][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_23), .Q (\mem[3] [0]));
  decrq1 \mem_reg[3][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_23), .Q (\mem[3] [1]));
  decrq1 \mem_reg[3][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_23), .Q (\mem[3] [2]));
  decrq1 \mem_reg[3][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_23), .Q (\mem[3] [3]));
  decrq1 \mem_reg[3][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_23), .Q (\mem[3] [4]));
  decrq1 \mem_reg[3][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_23), .Q (\mem[3] [5]));
  decrq1 \mem_reg[3][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_23), .Q (\mem[3] [6]));
  decrq1 \mem_reg[3][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_23), .Q (\mem[3] [7]));
  decrq1 \mem_reg[4][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_17), .Q (\mem[4] [0]));
  decrq1 \mem_reg[4][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_17), .Q (\mem[4] [1]));
  decrq1 \mem_reg[4][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_17), .Q (\mem[4] [2]));
  decrq1 \mem_reg[4][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_17), .Q (\mem[4] [3]));
  decrq1 \mem_reg[4][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_17), .Q (\mem[4] [4]));
  decrq1 \mem_reg[4][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_17), .Q (\mem[4] [5]));
  decrq1 \mem_reg[4][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_17), .Q (\mem[4] [6]));
  decrq1 \mem_reg[4][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_17), .Q (\mem[4] [7]));
  decrq1 \mem_reg[5][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_21), .Q (\mem[5] [0]));
  decrq1 \mem_reg[5][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_21), .Q (\mem[5] [1]));
  decrq1 \mem_reg[5][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_21), .Q (\mem[5] [2]));
  decrq1 \mem_reg[5][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_21), .Q (\mem[5] [3]));
  decrq1 \mem_reg[5][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_21), .Q (\mem[5] [4]));
  decrq1 \mem_reg[5][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_21), .Q (\mem[5] [5]));
  decrq1 \mem_reg[5][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_21), .Q (\mem[5] [6]));
  decrq1 \mem_reg[5][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_21), .Q (\mem[5] [7]));
  decrq1 \mem_reg[6][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_10), .Q (\mem[6] [0]));
  decrq1 \mem_reg[6][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_10), .Q (\mem[6] [1]));
  decrq1 \mem_reg[6][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_10), .Q (\mem[6] [2]));
  decrq1 \mem_reg[6][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_10), .Q (\mem[6] [3]));
  decrq1 \mem_reg[6][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_10), .Q (\mem[6] [4]));
  decrq1 \mem_reg[6][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_10), .Q (\mem[6] [5]));
  decrq1 \mem_reg[6][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_10), .Q (\mem[6] [6]));
  decrq1 \mem_reg[6][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_10), .Q (\mem[6] [7]));
  decrq1 \mem_reg[7][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_20), .Q (\mem[7] [0]));
  decrq1 \mem_reg[7][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_20), .Q (\mem[7] [1]));
  decrq1 \mem_reg[7][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_20), .Q (\mem[7] [2]));
  decrq1 \mem_reg[7][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_20), .Q (\mem[7] [3]));
  decrq1 \mem_reg[7][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_20), .Q (\mem[7] [4]));
  decrq1 \mem_reg[7][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_20), .Q (\mem[7] [5]));
  decrq1 \mem_reg[7][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_20), .Q (\mem[7] [6]));
  decrq1 \mem_reg[7][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_20), .Q (\mem[7] [7]));
  decrq1 \mem_reg[8][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_14), .Q (\mem[8] [0]));
  decrq1 \mem_reg[8][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_14), .Q (\mem[8] [1]));
  decrq1 \mem_reg[8][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_14), .Q (\mem[8] [2]));
  decrq1 \mem_reg[8][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_14), .Q (\mem[8] [3]));
  decrq1 \mem_reg[8][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_14), .Q (\mem[8] [4]));
  decrq1 \mem_reg[8][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_14), .Q (\mem[8] [5]));
  decrq1 \mem_reg[8][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_14), .Q (\mem[8] [6]));
  decrq1 \mem_reg[8][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_14), .Q (\mem[8] [7]));
  decrq1 \mem_reg[9][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_11), .Q (\mem[9] [0]));
  decrq1 \mem_reg[9][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_11), .Q (\mem[9] [1]));
  decrq1 \mem_reg[9][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_11), .Q (\mem[9] [2]));
  decrq1 \mem_reg[9][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_11), .Q (\mem[9] [3]));
  decrq1 \mem_reg[9][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_11), .Q (\mem[9] [4]));
  decrq1 \mem_reg[9][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_11), .Q (\mem[9] [5]));
  decrq1 \mem_reg[9][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_11), .Q (\mem[9] [6]));
  decrq1 \mem_reg[9][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_11), .Q (\mem[9] [7]));
  decrq1 \mem_reg[10][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_18), .Q (\mem[10] [0]));
  decrq1 \mem_reg[10][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_18), .Q (\mem[10] [1]));
  decrq1 \mem_reg[10][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_18), .Q (\mem[10] [2]));
  decrq1 \mem_reg[10][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_18), .Q (\mem[10] [3]));
  decrq1 \mem_reg[10][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_18), .Q (\mem[10] [4]));
  decrq1 \mem_reg[10][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_18), .Q (\mem[10] [5]));
  decrq1 \mem_reg[10][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_18), .Q (\mem[10] [6]));
  decrq1 \mem_reg[10][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_18), .Q (\mem[10] [7]));
  decrq1 \mem_reg[11][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_24), .Q (\mem[11] [0]));
  decrq1 \mem_reg[11][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_24), .Q (\mem[11] [1]));
  decrq1 \mem_reg[11][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_24), .Q (\mem[11] [2]));
  decrq1 \mem_reg[11][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_24), .Q (\mem[11] [3]));
  decrq1 \mem_reg[11][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_24), .Q (\mem[11] [4]));
  decrq1 \mem_reg[11][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_24), .Q (\mem[11] [5]));
  decrq1 \mem_reg[11][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_24), .Q (\mem[11] [6]));
  decrq1 \mem_reg[11][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_24), .Q (\mem[11] [7]));
  decrq1 \mem_reg[12][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_25), .Q (\mem[12] [0]));
  decrq1 \mem_reg[12][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_25), .Q (\mem[12] [1]));
  decrq1 \mem_reg[12][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_25), .Q (\mem[12] [2]));
  decrq1 \mem_reg[12][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_25), .Q (\mem[12] [3]));
  decrq1 \mem_reg[12][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_25), .Q (\mem[12] [4]));
  decrq1 \mem_reg[12][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_25), .Q (\mem[12] [5]));
  decrq1 \mem_reg[12][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_25), .Q (\mem[12] [6]));
  decrq1 \mem_reg[12][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_25), .Q (\mem[12] [7]));
  decrq1 \mem_reg[13][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_13), .Q (\mem[13] [0]));
  decrq1 \mem_reg[13][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_13), .Q (\mem[13] [1]));
  decrq1 \mem_reg[13][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_13), .Q (\mem[13] [2]));
  decrq1 \mem_reg[13][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_13), .Q (\mem[13] [3]));
  decrq1 \mem_reg[13][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_13), .Q (\mem[13] [4]));
  decrq1 \mem_reg[13][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_13), .Q (\mem[13] [5]));
  decrq1 \mem_reg[13][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_13), .Q (\mem[13] [6]));
  decrq1 \mem_reg[13][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_13), .Q (\mem[13] [7]));
  decrq1 \mem_reg[14][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_19), .Q (\mem[14] [0]));
  decrq1 \mem_reg[14][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_19), .Q (\mem[14] [1]));
  decrq1 \mem_reg[14][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_19), .Q (\mem[14] [2]));
  decrq1 \mem_reg[14][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_19), .Q (\mem[14] [3]));
  decrq1 \mem_reg[14][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_19), .Q (\mem[14] [4]));
  decrq1 \mem_reg[14][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_19), .Q (\mem[14] [5]));
  decrq1 \mem_reg[14][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_19), .Q (\mem[14] [6]));
  decrq1 \mem_reg[14][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_19), .Q (\mem[14] [7]));
  decrq1 \mem_reg[15][0] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[0]), .ENN (n_22), .Q (\mem[15] [0]));
  decrq1 \mem_reg[15][1] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[1]), .ENN (n_22), .Q (\mem[15] [1]));
  decrq1 \mem_reg[15][2] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[2]), .ENN (n_22), .Q (\mem[15] [2]));
  decrq1 \mem_reg[15][3] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[3]), .ENN (n_22), .Q (\mem[15] [3]));
  decrq1 \mem_reg[15][4] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[4]), .ENN (n_22), .Q (\mem[15] [4]));
  decrq1 \mem_reg[15][5] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[5]), .ENN (n_22), .Q (\mem[15] [5]));
  decrq1 \mem_reg[15][6] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[6]), .ENN (n_22), .Q (\mem[15] [6]));
  decrq1 \mem_reg[15][7] (.CDN (i_wr_rst_n), .CP (i_wr_clk), .D
       (i_wr_data[7]), .ENN (n_22), .Q (\mem[15] [7]));
  or03d1 g1982__5477(.A1 (n_144), .A2 (n_9), .A3 (n_8), .Z (n_25));
  or03d1 g1983__2398(.A1 (n_144), .A2 (n_1), .A3 (n_2), .Z (n_24));
  or03d1 g1984__5107(.A1 (n_144), .A2 (n_2), .A3 (n_7), .Z (n_23));
  or03d1 g1985__6260(.A1 (n_144), .A2 (n_0), .A3 (n_1), .Z (n_22));
  or03d1 g1986__4319(.A1 (n_144), .A2 (n_8), .A3 (n_7), .Z (n_21));
  or03d1 g1987__8428(.A1 (n_144), .A2 (n_0), .A3 (n_7), .Z (n_20));
  or03d1 g1988__5526(.A1 (n_144), .A2 (n_0), .A3 (n_9), .Z (n_19));
  or03d1 g1989__6783(.A1 (n_144), .A2 (n_9), .A3 (n_2), .Z (n_18));
  nd13d1 g1990__3680(.A1 (n_8), .A2 (n_5), .A3 (n_3), .ZN (n_17));
  nd03d1 g1991__1617(.A1 (n_5), .A2 (n_3), .A3 (n_4), .ZN (n_16));
  nd13d1 g1992__2802(.A1 (n_7), .A2 (n_5), .A3 (n_4), .ZN (n_15));
  nd13d1 g1993__1705(.A1 (n_9), .A2 (n_5), .A3 (n_4), .ZN (n_14));
  or03d1 g1994__5122(.A1 (n_144), .A2 (n_1), .A3 (n_8), .Z (n_13));
  nd13d1 g1995__8246(.A1 (n_2), .A2 (n_5), .A3 (n_3), .ZN (n_12));
  nd13d1 g1996__7098(.A1 (n_1), .A2 (n_5), .A3 (n_4), .ZN (n_11));
  nd13d1 g1997__6131(.A1 (n_0), .A2 (n_5), .A3 (n_3), .ZN (n_10));
  inv0d1 g1998(.I (n_144), .ZN (n_5));
  nd12d1 g1999__1881(.A1 (i_wr_addr[0]), .A2 (i_wr_addr[3]), .ZN (n_9));
  nd12d1 g2000__5115(.A1 (i_wr_addr[1]), .A2 (i_wr_addr[2]), .ZN (n_8));
  nd12d1 g2001__7482(.A1 (i_wr_addr[3]), .A2 (i_wr_addr[0]), .ZN (n_7));
  nr02d1 g2003__6161(.A1 (i_wr_addr[1]), .A2 (i_wr_addr[2]), .ZN (n_4));
  nr02d1 g2004__9315(.A1 (i_wr_addr[0]), .A2 (i_wr_addr[3]), .ZN (n_3));
  nd12d1 g2005__9945(.A1 (i_wr_addr[2]), .A2 (i_wr_addr[1]), .ZN (n_2));
  nd02d1 g2006__2883(.A1 (i_wr_addr[3]), .A2 (i_wr_addr[0]), .ZN (n_1));
  nd02d1 g2007__2346(.A1 (i_wr_addr[2]), .A2 (i_wr_addr[1]), .ZN (n_0));
  nd12d1 g2(.A1 (i_full), .A2 (i_wr_en), .ZN (n_144));
endmodule

module reset_sync(o_sync_rst, i_clk, i_rst_n);
  input i_clk, i_rst_n;
  output o_sync_rst;
  wire i_clk, i_rst_n;
  wire o_sync_rst;
  wire syncrst_reg;
  dfcrq1 o_sync_rst_reg(.CDN (i_rst_n), .CP (i_clk), .D (syncrst_reg),
       .Q (o_sync_rst));
  dfcrq1 syncrst_reg_reg(.CDN (i_rst_n), .CP (i_clk), .D (1'b1), .Q
       (syncrst_reg));
endmodule

module sync_ptr_clx_ADDRSIZE4(o_ptr_clx, i_ptr, i_clk, i_rst_n);
  input [4:0] i_ptr;
  input i_clk, i_rst_n;
  output [4:0] o_ptr_clx;
  wire [4:0] i_ptr;
  wire i_clk, i_rst_n;
  wire [4:0] o_ptr_clx;
  wire [4:0] ptr_clx_r;
  dfcrq1 \o_ptr_clx_reg[4] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[4]), .Q (o_ptr_clx[4]));
  dfcrq1 \o_ptr_clx_reg[3] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[3]), .Q (o_ptr_clx[3]));
  dfcrq1 \o_ptr_clx_reg[1] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[1]), .Q (o_ptr_clx[1]));
  dfcrq1 \o_ptr_clx_reg[0] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[0]), .Q (o_ptr_clx[0]));
  dfcrq1 \o_ptr_clx_reg[2] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[2]), .Q (o_ptr_clx[2]));
  dfcrq1 \ptr_clx_r_reg[2] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[2]),
       .Q (ptr_clx_r[2]));
  dfcrq1 \ptr_clx_r_reg[3] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[3]),
       .Q (ptr_clx_r[3]));
  dfcrq1 \ptr_clx_r_reg[4] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[4]),
       .Q (ptr_clx_r[4]));
  dfcrq1 \ptr_clx_r_reg[0] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[0]),
       .Q (ptr_clx_r[0]));
  dfcrq1 \ptr_clx_r_reg[1] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[1]),
       .Q (ptr_clx_r[1]));
endmodule

module sync_ptr_clx_ADDRSIZE4_34(o_ptr_clx, i_ptr, i_clk, i_rst_n);
  input [4:0] i_ptr;
  input i_clk, i_rst_n;
  output [4:0] o_ptr_clx;
  wire [4:0] i_ptr;
  wire i_clk, i_rst_n;
  wire [4:0] o_ptr_clx;
  wire [4:0] ptr_clx_r;
  dfcrq1 \o_ptr_clx_reg[4] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[4]), .Q (o_ptr_clx[4]));
  dfcrq1 \o_ptr_clx_reg[3] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[3]), .Q (o_ptr_clx[3]));
  dfcrq1 \o_ptr_clx_reg[1] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[1]), .Q (o_ptr_clx[1]));
  dfcrq1 \o_ptr_clx_reg[0] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[0]), .Q (o_ptr_clx[0]));
  dfcrq1 \o_ptr_clx_reg[2] (.CDN (i_rst_n), .CP (i_clk), .D
       (ptr_clx_r[2]), .Q (o_ptr_clx[2]));
  dfcrq1 \ptr_clx_r_reg[2] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[2]),
       .Q (ptr_clx_r[2]));
  dfcrq1 \ptr_clx_r_reg[3] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[3]),
       .Q (ptr_clx_r[3]));
  dfcrq1 \ptr_clx_r_reg[4] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[4]),
       .Q (ptr_clx_r[4]));
  dfcrq1 \ptr_clx_r_reg[0] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[0]),
       .Q (ptr_clx_r[0]));
  dfcrq1 \ptr_clx_r_reg[1] (.CDN (i_rst_n), .CP (i_clk), .D (i_ptr[1]),
       .Q (ptr_clx_r[1]));
endmodule

module reset_sync_33(o_sync_rst, i_clk, i_rst_n);
  input i_clk, i_rst_n;
  output o_sync_rst;
  wire i_clk, i_rst_n;
  wire o_sync_rst;
  wire syncrst_reg;
  dfcrq1 o_sync_rst_reg(.CDN (i_rst_n), .CP (i_clk), .D (syncrst_reg),
       .Q (o_sync_rst));
  dfcrq1 syncrst_reg_reg(.CDN (i_rst_n), .CP (i_clk), .D (1'b1), .Q
       (syncrst_reg));
endmodule

module fifo(o_rd_data_pad, o_full_pad, o_empty_pad, i_wr_data_pad,
     i_wr_en_pad, i_wr_clk_pad, i_wr_rst_n_pad, i_rd_en_pad,
     i_rd_clk_pad, i_rd_rst_n_pad);
  input [7:0] i_wr_data_pad;
  input i_wr_en_pad, i_wr_clk_pad, i_wr_rst_n_pad, i_rd_en_pad,
       i_rd_clk_pad, i_rd_rst_n_pad;
  output [7:0] o_rd_data_pad;
  output o_full_pad, o_empty_pad;
  wire [7:0] i_wr_data_pad;
  wire i_wr_en_pad, i_wr_clk_pad, i_wr_rst_n_pad, i_rd_en_pad,
       i_rd_clk_pad, i_rd_rst_n_pad;
  wire [7:0] o_rd_data_pad;
  wire o_full_pad, o_empty_pad;
  wire [7:0] i_wr_data;
  wire [7:0] o_rd_data;
  wire [4:0] wr_ptr_clx;
  wire [3:0] rd_addr_s;
  wire [4:0] rd_ptr_s;
  wire [4:0] rd_ptr_clx;
  wire [3:0] wr_addr_s;
  wire [4:0] wr_ptr_s;
  wire i_rd_clk, i_rd_en, i_rd_rst_n, i_wr_clk, i_wr_en, i_wr_rst_n,
       o_empty, o_full;
  wire read_clk, sync_rd_rst, sync_wr_rst, write_clk;
  fifo_empty_ADDRSIZE4 u_fifo_empty(.i_rd_clk (i_rd_clk), .i_rd_rst_n
       (sync_rd_rst), .i_rd_en (i_rd_en), .i_wr_ptr_clx (wr_ptr_clx),
       .o_empty (o_empty), .o_rd_addr (rd_addr_s), .o_rd_ptr
       (rd_ptr_s));
  fifo_full_ADDRSIZE4 u_fifo_full(.i_wr_clk (i_wr_clk), .i_wr_rst_n
       (sync_wr_rst), .i_wr_en (i_wr_en), .i_rd_ptr_clx (rd_ptr_clx),
       .o_full (o_full), .o_wr_addr (wr_addr_s), .o_wr_ptr (wr_ptr_s));
  fifo_mem_DATASIZE8_ADDRSIZE4_MEM_DEPTH16 u_fifo_mem(.o_rd_data
       (o_rd_data), .i_full (o_full), .i_wr_data (i_wr_data), .i_wr_clk
       (i_wr_clk), .i_wr_en (i_wr_en), .i_wr_addr (wr_addr_s),
       .i_rd_addr (rd_addr_s), .i_wr_rst_n (sync_wr_rst));
  reset_sync u_rd_reset_sync(.o_sync_rst (sync_rd_rst), .i_clk
       (i_rd_clk), .i_rst_n (i_rd_rst_n));
  sync_ptr_clx_ADDRSIZE4 u_sync_rd2wr_clx(.o_ptr_clx (rd_ptr_clx),
       .i_ptr (rd_ptr_s), .i_clk (i_wr_clk), .i_rst_n (sync_wr_rst));
  sync_ptr_clx_ADDRSIZE4_34 u_sync_wr2rd_clx(.o_ptr_clx (wr_ptr_clx),
       .i_ptr (wr_ptr_s), .i_clk (i_rd_clk), .i_rst_n (sync_rd_rst));
  reset_sync_33 u_wr_reset_sync(.o_sync_rst (sync_wr_rst), .i_clk
       (i_wr_clk), .i_rst_n (i_wr_rst_n));
  pc3c01 pc3c01_1(.CCLK (read_clk), .CP (i_rd_clk));
  pc3c01 pc3c01_2(.CCLK (write_clk), .CP (i_wr_clk));
  pc3d01 pc3d01_1(.PAD (i_rd_clk_pad), .CIN (read_clk));
  pc3d01 pc3d01_2(.PAD (i_wr_clk_pad), .CIN (write_clk));
  pc3d01 pc3d01_3(.PAD (i_wr_rst_n_pad), .CIN (i_wr_rst_n));
  pc3d01 pc3d01_4(.PAD (i_rd_rst_n_pad), .CIN (i_rd_rst_n));
  pc3d01 pc3d01_5(.PAD (i_wr_en_pad), .CIN (i_wr_en));
  pc3d01 pc3d01_6(.PAD (i_rd_en_pad), .CIN (i_rd_en));
  pc3d01 pc3d01_7(.PAD (i_wr_data_pad[7]), .CIN (i_wr_data[7]));
  pc3d01 pc3d01_8(.PAD (i_wr_data_pad[6]), .CIN (i_wr_data[6]));
  pc3d01 pc3d01_9(.PAD (i_wr_data_pad[5]), .CIN (i_wr_data[5]));
  pc3d01 pc3d01_10(.PAD (i_wr_data_pad[4]), .CIN (i_wr_data[4]));
  pc3d01 pc3d01_11(.PAD (i_wr_data_pad[3]), .CIN (i_wr_data[3]));
  pc3d01 pc3d01_12(.PAD (i_wr_data_pad[2]), .CIN (i_wr_data[2]));
  pc3d01 pc3d01_13(.PAD (i_wr_data_pad[1]), .CIN (i_wr_data[1]));
  pc3d01 pc3d01_14(.PAD (i_wr_data_pad[0]), .CIN (i_wr_data[0]));
  pc3o05 pc3o05_1(.I (o_rd_data[7]), .PAD (o_rd_data_pad[7]));
  pc3o05 pc3o05_2(.I (o_rd_data[6]), .PAD (o_rd_data_pad[6]));
  pc3o05 pc3o05_3(.I (o_rd_data[5]), .PAD (o_rd_data_pad[5]));
  pc3o05 pc3o05_4(.I (o_rd_data[4]), .PAD (o_rd_data_pad[4]));
  pc3o05 pc3o05_5(.I (o_rd_data[3]), .PAD (o_rd_data_pad[3]));
  pc3o05 pc3o05_6(.I (o_rd_data[2]), .PAD (o_rd_data_pad[2]));
  pc3o05 pc3o05_7(.I (o_rd_data[1]), .PAD (o_rd_data_pad[1]));
  pc3o05 pc3o05_8(.I (o_rd_data[0]), .PAD (o_rd_data_pad[0]));
  pc3o05 pc3o05_9(.I (o_full), .PAD (o_full_pad));
  pc3o05 pc3o05_10(.I (o_empty), .PAD (o_empty_pad));

  pvdi   pvdi_VDD_CORE_1   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0i   pv0i_VSS_CORE_1   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda   pvda_VDDO_CORE_1  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a   pv0a_VSSO_CORE_1  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));

  pvdi   pvdi_VDD_CORE_2   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0i   pv0i_VSS_CORE_2   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda   pvda_VDDO_CORE_2  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a   pv0a_VSSO_CORE_2  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));

  pvdi   pvdi_VDD_CORE_3   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0i   pv0i_VSS_CORE_3   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda   pvda_VDDO_CORE_3  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a   pv0a_VSSO_CORE_3  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));

  pvdi   pvdi_VDD_CORE_4   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0i   pv0i_VSS_CORE_4   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda   pvda_VDDO_CORE_4  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a   pv0a_VSSO_CORE_4  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));

  pvdi   pvdi_VDD_CORE_5   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0i   pv0i_VSS_CORE_5   (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pvda   pvda_VDDO_CORE_5  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));
  pv0a   pv0a_VSSO_CORE_5  (.VDD(VDD_CORE), .VSS(VSS_CORE), .VDDO(VDDO_CORE), .VSSO(VSSO_CORE));

endmodule

